// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DefineEmits: typeof import('./src/components/DefineEmits.vue')['default']
    DefineProps: typeof import('./src/components/DefineProps.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SetupScript: typeof import('./src/components/SetupScript.vue')['default']
    TodoAdd: typeof import('./src/components/TodoAdd.vue')['default']
    TodoFilter: typeof import('./src/components/TodoFilter.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    TodoListItem: typeof import('./src/components/TodoListItem.vue')['default']
  }
}

export { }
